### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by enea1982** [alxmamaev/fastcoinbot#1]
Hello can you help me to install the bot gives me an error and I do not know how to make the link to webhok gives me this error :  Traceback (most recent call last):
   File "app.py", line 3, in <module>
     import flask
ImportError: No module named 'flask'

**Comment by enea1982** [comment]
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    WEBHOOK_URL = os.environ["WEBHOOK_URL"]+"/bot/"+os.environ["BOT_TOKEN"]
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'WEBHOOK_URL'
this error

**Comment by enea1982** [comment]
hi ?
